### ISSUE TITLE
Css bundling selectors to gain same effect

### ISSUE THREAD

**Issue by Emik234** [cmay84/prj-rev-bwfs-dasmoto#1]
A better way to go about adding font family Helvetica along with a backup font is to grab multiple selectors and bundle them with the font family property. This eliminates the need to keep putting the same property across all the selectors Ex: 

```
h1, h2, h3, p {
  font-family: "Helvetica", sans-serif;
} 
```

**Comment by cmay84** [comment]
I see, awesome, thanks Emik!
